name: Deploy React App
on:
  push:
    branches: ["main"] # Ensure this matches your main branch name
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # If you use Vite, change 'build' to 'dist'
          path: './build' 

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
